### ISSUE TITLE
Is it possible to assigne the result from a sql execution to variable?

### ISSUE THREAD

**Issue by paulhybryant** [datarho/asqlcell#24]
e.g.

df = pd.read_csv(...)

%%sql

SELECT * FROM df WHERE ...

I want to assign the resultfrom the sql to another dataframe df2

**Comment by Zhuhd233** [comment]
%%sql df2

SELECT * FROM df WHERE ...

You can solve this problem in this way:)

**Comment by Zhuhd233** [comment]
Closed
